services:
  app1:
    container_name: busybox1
    image: busybox
    entrypoint: /bin/sh
    command: -c "while true; do echo F1 $(date +%s); ls -la /test-data; sleep 5; done"
    environment:
      TESTER1: BLA1
    volumes:
        - ../test-doco-cd2/test_data:/test-data