services:
  app1:
    container_name: busybox1
    image: busybox
    entrypoint: /bin/sh
    command: -c "while true; do echo F1 A${TESTER}A $(date +%s); ls -la /test-data; sleep 5; done"
    volumes:
        - ./data1:/test-data
        #- ../test-doco-cd2/test_data:/test-data
